Customer Churn Prediction

In [104]:
import sys
sys.path.append("..")

In [105]:
import pandas as pd # working with datassets
import numpy as np # numerical operations
import matplotlib.pyplot as plt #creating visualization
import seaborn as sns # creating stastical graphs

In [106]:
df=pd.read_csv(r"C:\Users\NIKHILA\Downloads\archive\WA_Fn-UseC_-Telco-Customer-Churn.csv")  #loading the CSV into a Dataframe called df
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [107]:
df.head()  # shows the first 5 rows

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [108]:
df.shape #shows the number of rows and columns

(7043, 21)

In [109]:
df.columns  #shows all the columns names in our dataset

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

We are doing EDA--Exploratort Data Analysis

In [110]:
df.info()  # shows column names,number of values and data types  ++++++

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [111]:
df.isnull().sum()  # counting missinng values in each column

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [112]:
df.duplicated().sum()  # counts duplicate rows in the dataset

np.int64(0)

In [113]:
df["Churn"].value_counts() #counts customers who stayed and customers who left
# churn means if yes==customer left the company
# if no== customer stayed with the company

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [114]:
df["Churn"].value_counts(normalize=True) #calculates the percentage of yes and no customers
# normalize=True  which gives proportions/percentages

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [115]:
0.73463*100  #stayed

73.463

In [116]:
0.26537*100  # churned

26.537

In [117]:
df.dtypes # shows the data types of every column

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [118]:
df.duplicated().sum() #counts completely duplicates rows

np.int64(0)

In [119]:
df.nunique()  # shows the number of unique values in each column

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [120]:
df.describe() # shows statistical summary of numerical columns

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [121]:
# checking categorical columns
df['gender'].value_counts() #counts male and female customers

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [122]:
 ## contract tells us how long the customers agreement is
df['Contract'].value_counts()  # counnts customers for each contract type

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [123]:
## lets check internet service,because the type of internet service may affect whether customers leave
df["InternetService"].value_counts() #counts customers for each internet service type

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [124]:
## checking target variable against these features
pd.crosstab(df['Contract'],df['Churn']) # compares contarct type with churn

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [125]:
## lets check InternetService vs Churn
pd.crosstab(df['InternetService'],df['Churn']) ## compares InternetService with churn

Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

In [126]:
df.groupby('Churn')['tenure'].mean() #calculates average tenure for customers who stayed and left

Churn
No     37.569965
Yes    17.979133
Name: tenure, dtype: float64

In [127]:
df.groupby('Churn')['MonthlyCharges'].mean()  #calculates average monthly charge for customers who stayed and left

Churn
No     61.265124
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [128]:
## checking payment method vs churn
pd.crosstab(df['PaymentMethod'],df['Churn']) # compares payment methods e=with customer churn

Churn                        No   Yes
PaymentMethod
Bank transfer (automatic)  1286   258
Credit card (automatic)    1290   232
Electronic check           1294  1071
Mailed check               1304   308

In [129]:
pd.crosstab(df['Contract'],df['Churn'],normalize='index')*100  #calculates the churn percentage for each contract type
## index means calculates the percentage within each contract type

Churn                  No        Yes
Contract
Month-to-month  57.290323  42.709677
One year        88.730482  11.269518
Two year        97.168142   2.831858

In [130]:
pd.crosstab(df['SeniorCitizen'],df['Churn'],normalize='index')*100  # calculates the churn percentage for each senior citizen group

Churn                 No        Yes
SeniorCitizen
0              76.393832  23.606168
1              58.318739  41.681261

In [131]:
pd.crosstab(df['InternetService'],df['Churn'],normalize='index')*100  # calculates the churn percentage for each Internet service type

Churn                   No        Yes
InternetService
DSL              81.040892  18.959108
Fiber optic      58.107235  41.892765
No               92.595020   7.404980

In [132]:
## checking missing values
df.isnull().sum() ## checking how many missing values are present in each column
## isnull() checks whether a value is missing
## sum() counts those missing values

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [133]:
## remove customer id because it is just an identification number.it doesnt provide useful information for predecting whether a customer will churn

df.drop('customerID',axis=1,inplace=True) #removes the customerID column because it is only an identifier
## axis=1 tells pandas that customerID is a column
## inplace=True makes the change directly in df

In [134]:
df.columns  #shows the remaining columns names

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

Separate features(X) and target(y)

In [135]:
X=df.drop('Churn',axis=1) #creates X containing all input features expect the target column churn
y=df['Churn'] #creates y containing only the target variable Churn

In [136]:
X.shape # shows the number of rows and columns in X

(7043, 19)

In [137]:
y.shape # shows the  umber values in y

(7043,)

Now we need to split the data into training and testing data

In [138]:
from sklearn.model_selection import train_test_split #imports the function used to split data into training and testing sets

In [139]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) #splits the data into 8-% training and 20% testing data
#random_state=42 makes sure we get the same split every time we run the code

In [140]:
X_train.shape #shows the rows and columns in training features

(5634, 19)

In [141]:
X_test.shape #shows the rows and columns in testing features

(1409, 19)

In [142]:
y_train.shape #shows the number of target values used for training

(5634,)

In [143]:
y_test.shape #shows the number of target values used for testing

(1409,)

Convert text into Numbers

In [144]:
X_train.dtypes #shows the data type of every feature in X_train

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
dtype: object

In [145]:
X_train['TotalCharges']=pd.to_numeric(X_train['TotalCharges'],errors='coerce') #converts TotalCharges from text to numbers;invalid values become NaN
#errors='coerce'--- sometimes column containss something that cannot be converted into numbers ,such as an empty string,Instead of giving error we will use this it changes the invalid values into "NaN"(it means missing values)

In [146]:
X_test['TotalCharges']=pd.to_numeric(X_test['TotalCharges'],errors='coerce') #converts TotalCharges from text to numbers in the test data

In [147]:
X_train.dtypes  # checking whether Totalcharges has been converted to a numeric  type

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
dtype: object

In [148]:
X_train['TotalCharges'].isna().sum() # counts how many missing values are present in TOtal charges

np.int64(10)

In [149]:
X_test['TotalCharges'].isna().sum() # counts missing values in test data

np.int64(1)

In [150]:
X_train['TotalCharges']=X_train['TotalCharges'].fillna(X_train['TotalCharges'].median()) #it fills missing Totalcharges values with the training median

In [151]:
X_train['TotalCharges'].isna().sum()

np.int64(0)

In [152]:
X_test['TotalCharges'].isna().sum()

np.int64(1)

Encoding

In [153]:
X_train.select_dtypes(include='object').columns  #shows all text/categorical columns that need encoding

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

One-Hot-Encoding

In [154]:
X_train=pd.get_dummies(X_train,drop_first=True)
X_test=pd.get_dummies(X_test,drop_first=True) # converts text categories into numerical columns
#get_dummies() performs one hot encoding,it converts categories into 0 and 1
#drop_first=True----this removes one category from each categorical column

In [155]:
X_train.shape

(5634, 30)

In [156]:
X_test.shape

(1409, 30)

Check for any missing values again

In [157]:
X_train.isna().sum().sum()# counts the total number of missing values in X_train
#first sum() counts missing values column by column
#second sum() adds all those column totals together to give one final number

np.int64(0)

In [158]:
X_test.isna().sum().sum()

np.int64(1)

In [159]:
X_test=X_test.fillna(X_train.median(numeric_only=True)) #fills the missing value in X_test using the median from X_train
#numeric_only=True-- means only numeric columns are considered
#fillna() means fill the missing values NaN and replaces that missing value with the appropriate median

In [160]:
X_test.isna().sum().sum() #checks whether any missing values remain

np.int64(0)

Feature Scaling

In [161]:
from sklearn.preprocessing import StandardScaler  ##import standardscaler for scaling numerical features
##StandardScaler --it changes numerical values to a common scale

In [162]:
scaler=StandardScaler()# creates a StandardScaler object that we will use for scale for features
X_train_scaled=scaler.fit_transform(X_train) #learns the scaling parameters from X_train and then scales X_train
#fit() learns from the training data
#transform() uses those values to scale the data

In [163]:
X_test_scaled=scaler.transform(X_test) #scales X_test using the same scaling learned fron X_train-
#X_train--learn the scaling + scale it
#X_test--only apply the learned scaling

In [164]:
X_train_scaled.shape #shows the number of rows and columns in the scaled training data

(5634, 30)

In [165]:
X_test_scaled.shape #shows the number of rows and columns in the scaled test data

(1409, 30)

Train our first model

In [166]:
from sklearn.linear_model import LogisticRegression #import LogisticRegression for predicting customer churn

In [167]:
model=LogisticRegression(max_iter=1000) #creates a LogisticRegression model

In [168]:
model.fit(X_train_scaled,y_train) #trains the model using training data

LogisticRegression(max_iter=1000)

Make Predictions

In [169]:
y_pred=model.predict(X_test_scaled) #predicts churn for the test customers

Check how good the predictions are

In [170]:
from sklearn.metrics import accuracy_score #imports the accuracy calculations
accuracy=accuracy_score(y_test,y_pred) #compares actual values with predicted values

In [171]:
accuracy #dispalys the accuracy

0.8197303051809794

Confusion matrix

In [172]:
from sklearn.metrics import confusion_matrix #import the confusion matrix function
cm=confusion_matrix(y_test,y_pred) #compares actual and predicted churn values
cm # displays the confusion matrix

array([[933, 103],
       [151, 222]])

clasification report

In [173]:
from sklearn.metrics import classification_report #import classification report function---it gives us a detailed evaluation of our LogisticRegression model
print(classification_report(y_test,y_pred))# shows precision,recall,F1-score and Support
#Precision---How many predicted churn customers were actually churn customers
#Recall---How many actual churnn customers the model successfully found
#F1-score----combination of precision and recall
#Support--Number of actual customers in each class

              precision    recall  f1-score   support

          No       0.86      0.90      0.88      1036
         Yes       0.68      0.60      0.64       373

    accuracy                           0.82      1409
   macro avg       0.77      0.75      0.76      1409
weighted avg       0.81      0.82      0.82      1409

In [174]:
from sklearn.ensemble import RandomForestClassifier #it is an ensemble technique--it  combines many decision trees to make a strong predictions

In [175]:
rf_model=RandomForestClassifier(n_estimators=100,random_state=42) #creates a Random Forest with 100 decidsion trees
#n_estimators=100------Random Forest will use 100 decision trees
#random_state=42----keeps the result reproducible,so u get the same resukt when u run it again

In [176]:
rf_model.fit(X_train_scaled,y_train) # trains the randomforest using the training data

RandomForestClassifier(random_state=42)

In [177]:
rf_pred=rf_model.predict(X_test_scaled)#predicts churn for the test customers

In [178]:
rf_accuracy=accuracy_score(y_test,rf_pred) #calculates how accurately RandomForest predicted churn or compares actual with predicted values

In [179]:
rf_accuracy

0.7899219304471257

In [180]:
print(classification_report(y_test,rf_pred)) #shows detailed RandomForest performance

              precision    recall  f1-score   support

          No       0.82      0.91      0.86      1036
         Yes       0.65      0.46      0.53       373

    accuracy                           0.79      1409
   macro avg       0.73      0.68      0.70      1409
weighted avg       0.78      0.79      0.78      1409

In [181]:

rf_cm=confusion_matrix(y_test,y_pred) #compares actual and predicted churn values
rf_cm # displays the confusion matrix

array([[933, 103],
       [151, 222]])

Compare the two models

In [182]:
print('LogisticRegression:',accuracy)
print('RandomForestClassifier:',rf_accuracy)

LogisticRegression: 0.8197303051809794
RandomForestClassifier: 0.7899219304471257

In [183]:
import os# gives python tools to work with folders and paths 
print(os.getcwd()) #shows the folder where the notebook is currently running

c:\Users\NIKHILA\OneDrive\Desktop\customer_churn_Prediction\notebooks

Save the Final model

In [184]:
import joblib ## import joblib for saving the trained model
joblib.dump(model,'../models/logistic_regression_model.pkl') # saves our logistic regression model
#joblib.dump()--saves an object to a file
#model--our trained LogisticRegression model
#'models'/logistic_regression_model.pkl---the location and filename where we will save it
#../models/'----mit means go one folder back frm notebooks,then enter models
#logistic_regression_model.pkl---the name of the saved model
#pkl---a Pyhton file format commonly used to store trained models

['../models/logistic_regression_model.pkl']

Save the Random Forest model

In [185]:
joblib.dump(rf_model,'../models/random_forest_model.pkl') # saves the random forest model

['../models/random_forest_model.pkl']

Save the Scaler

In [186]:
joblib.dump(scaler,'../models/scaler.pkl')#saves the scaler used during training 
#scaler----the scaler we used  earlier to scale X_train and X_test
# SCALER means---- converts new data into the same format the model expects

['../models/scaler.pkl']

In [187]:
X_train.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

New Customer Predictions
Create a sample customer

In [188]:
new_customer = pd.DataFrame([{
    'SeniorCitizen': 0,
    'tenure': 12,
    'MonthlyCharges': 70,
    'TotalCharges': 840,
    'gender_Male': 1,
    'Partner_Yes': 0,
    'Dependents_Yes': 0,
    'PhoneService_Yes': 1,
    'MultipleLines_No phone service': 0,
    'MultipleLines_Yes': 0,
    'InternetService_Fiber optic': 1,
    'InternetService_No': 0,
    'OnlineSecurity_No internet service': 0,
    'OnlineSecurity_Yes': 0,
    'OnlineBackup_No internet service': 0,
    'OnlineBackup_Yes': 0,
    'DeviceProtection_No internet service': 0,
    'DeviceProtection_Yes': 0,
    'TechSupport_No internet service': 0,
    'TechSupport_Yes': 0,
    'StreamingTV_No internet service': 0,
    'StreamingTV_Yes': 1,
    'StreamingMovies_No internet service': 0,
    'StreamingMovies_Yes': 1,
    'Contract_One year': 0,
    'Contract_Two year': 0,
    'PaperlessBilling_Yes': 1,
    'PaymentMethod_Credit card (automatic)': 0,
    'PaymentMethod_Electronic check': 1,
    'PaymentMethod_Mailed check': 0
}])

Scale the New Customer

In [189]:
new_customer_scaled=scaler.transform(new_customer) #scale the new customers data using the same scaler used during training
#scaler.transform----converts those values into the same scaled format used when training the model

Predict with LogisticRegression

In [190]:
lr_prediction=model.predict(new_customer_scaled)# predict whether the new customer will churn
print('Logistic Regression Prediction:',lr_prediction) # displays the prediction

Logistic Regression Prediction: ['Yes']

In [191]:
lr_probability=model.predict_proba(new_customer_scaled) # get the probability of churn for the new customer
print('Probability[No,Yes]:',lr_probability) #displays the probabilities
#predict_proba--means "tell me the probability of each possible class"

Probability[No,Yes]: [[0.22318304 0.77681696]]

Random Forest Prediction

In [192]:
rf_prediction=rf_model.predict(new_customer_scaled)#predict whether the new customer will churn using Random Forest
print('Random Forest Prediction:',rf_prediction)

Random Forest Prediction: ['Yes']

Get Random Forest probability

In [193]:
rf_probability=rf_model.predict_proba(new_customer_scaled)#get the probability of each class from Random Forest
print('Random Forest Probability[No,Yes]:',rf_probability)

Random Forest Probability[No,Yes]: [[0.4 0.6]]

Compare both Models

In [194]:
print('Model Comparison')
print('-------------')
print('Logistic Regression:',lr_prediction[0])
print('Logistic Regression Churn Probability:',lr_probability[0][1])

print('Random Forest:',rf_prediction[0])
print('Random Forest Churn Probability:',rf_probability[0][1])

#LogisticRegression gives the predictions from the LogisticRegression model
#Random Forest gives the predictions from the Random FOrest model
#we compare both predictions to see whether the two models agree
#[0]--selects the first row (our one customer)
#[1]--selects the second value in that row

Model Comparison
-------------
Logistic Regression: Yes
Logistic Regression Churn Probability: 0.7768169637148181
Random Forest: Yes
Random Forest Churn Probability: 0.6

In [195]:
lr_accuracy=accuracy_score(y_test,model.predict(X_test_scaled))
print('Logistic Regression Accuracy:',lr_accuracy)

Logistic Regression Accuracy: 0.8197303051809794

In [196]:
rf_accuracy=accuracy_score(y_test,rf_model.predict(X_test_scaled))
print('Random Forest Accuracy:',rf_accuracy)

Random Forest Accuracy: 0.7899219304471257

Create a final prediction function

In [197]:
#instead of manually writing all 33 values every time ,we will create a function where we can give customer details and get the churn prediction

def predict_churn(customer_data):

    customer_scaled = scaler.transform(customer_data)

    prediction = model.predict(customer_scaled)

    probability = model.predict_proba(customer_scaled)[0][1]

    result = prediction[0]

    print("Churn Prediction:", result)
    print("Churn Probability:", probability)

    return result, probability

In [198]:
customer_data=new_customer.iloc[[0]] #.values---converts it into an array
lr_prediction,lr_probability=predict_churn(customer_data)

Churn Prediction: Yes
Churn Probability: 0.7768169637148181

In [199]:
from src.predict import predict_churn

In [200]:
customer_data=new_customer.iloc[[0]]
lr_prediction,lr_probability=predict_churn(customer_data)

Churn Prediction: Yes
Churn Probability: 0.7768169637148181

In [201]:
print(model.classes_)

['No' 'Yes']

In [202]:
print(X.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges']

In [203]:
print(X.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges']

In [204]:
X_train=pd.get_dummies(X_train,drop_first=True)
X_test=pd.get_dummies(X_test,drop_first=True)

In [ ]:
import joblib
feature_columns=X_train.columns.tolist()
joblib.dump(feature_columns,"../models/feature_columns.pkl")

['../models/feature_columns.pkl']

In [208]:
import joblib
from pathlib import Path

In [ ]:
feature_columns=X_train.columns.tolist()

In [210]:
joblib.dump(feature_columns,"../models/feature_columns.pkl")

['../models/feature_columns.pkl']

In [211]:
from src.predict import predict_churn

In [212]:
feature_columns

['SeniorCitizen',
 'tenure',
 'MonthlyCharges',
 'TotalCharges',
 'gender_Male',
 'Partner_Yes',
 'Dependents_Yes',
 'PhoneService_Yes',
 'MultipleLines_No phone service',
 'MultipleLines_Yes',
 'InternetService_Fiber optic',
 'InternetService_No',
 'OnlineSecurity_No internet service',
 'OnlineSecurity_Yes',
 'OnlineBackup_No internet service',
 'OnlineBackup_Yes',
 'DeviceProtection_No internet service',
 'DeviceProtection_Yes',
 'TechSupport_No internet service',
 'TechSupport_Yes',
 'StreamingTV_No internet service',
 'StreamingTV_Yes',
 'StreamingMovies_No internet service',
 'StreamingMovies_Yes',
 'Contract_One year',
 'Contract_Two year',
 'PaperlessBilling_Yes',
 'PaymentMethod_Credit card (automatic)',
 'PaymentMethod_Electronic check',
 'PaymentMethod_Mailed check']

In [213]:
from src.predict import predict_churn

In [214]:
import pandas as pd

customer_data = pd.DataFrame(0, index=[0], columns=feature_columns)

customer_data["SeniorCitizen"] = 0
customer_data["tenure"] = 12
customer_data["MonthlyCharges"] = 70
customer_data["TotalCharges"] = 840

customer_data["gender_Male"] = 1
customer_data["Partner_Yes"] = 1
customer_data["Dependents_Yes"] = 0
customer_data["PhoneService_Yes"] = 1
customer_data["MultipleLines_Yes"] = 0
customer_data["InternetService_Fiber optic"] = 1
customer_data["OnlineSecurity_Yes"] = 0
customer_data["OnlineBackup_Yes"] = 0
customer_data["DeviceProtection_Yes"] = 0
customer_data["TechSupport_Yes"] = 0
customer_data["StreamingTV_Yes"] = 1
customer_data["StreamingMovies_Yes"] = 1
customer_data["Contract_One year"] = 0
customer_data["Contract_Two year"] = 0
customer_data["PaperlessBilling_Yes"] = 1
customer_data["PaymentMethod_Credit card (automatic)"] = 0
customer_data["PaymentMethod_Electronic check"] = 1
customer_data["PaymentMethod_Mailed check"] = 0

customer_data

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,12,70,840,1,1,0,1,0,0,...,0,1,0,1,0,0,1,0,1,0

In [215]:
predict_churn(customer_data)

Churn Prediction: Yes
Churn Probability: 0.786077252032639

('Yes', np.float64(0.786077252032639))